# Generated by Django 3.1.2 on 2020-10-29 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='datePosted',
        ),
    ]
